import { Lead, Property, Client, Deal, Task, User, DashboardMetrics } from '@/types/crm';

export const mockUsers: User[] = [
  { id: '1', name: 'John Smith', role: 'Admin', email: 'john@propertycrm.com', avatar: 'JS' },
  { id: '2', name: 'Sarah Wilson', role: 'Agent', email: 'sarah@propertycrm.com', avatar: 'SW' },
  { id: '3', name: 'Mike Chen', role: 'Agent', email: 'mike@propertycrm.com', avatar: 'MC' },
  { id: '4', name: 'Emma Davis', role: 'Owner', email: 'emma@propertycrm.com', avatar: 'ED' },
];

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    email: 'alex@email.com',
    phone: '+1 555 0123',
    source: 'Website',
    type: 'Buyer',
    tags: ['Hot Lead', 'First Time Buyer'],
    score: 85,
    status: 'Qualified',
    budgetMin: 800000,
    budgetMax: 1200000,
    locations: ['Downtown', 'Midtown'],
    assignedTo: '2',
    lastContactedAt: new Date('2024-01-15'),
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    name: 'Maria Rodriguez',
    email: 'maria@email.com',
    phone: '+1 555 0124',
    source: 'WhatsApp',
    type: 'Seller',
    tags: ['Urgent', 'Relocation'],
    score: 92,
    status: 'Negotiation',
    budgetMin: 1500000,
    budgetMax: 2000000,
    locations: ['Uptown'],
    assignedTo: '3',
    lastContactedAt: new Date('2024-01-18'),
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    name: 'David Kim',
    email: 'david@email.com',
    phone: '+1 555 0125',
    source: 'Referral',
    type: 'Buyer',
    tags: ['Investment', 'Cash Buyer'],
    score: 78,
    status: 'Visit Scheduled',
    budgetMin: 2000000,
    budgetMax: 3000000,
    locations: ['Waterfront', 'City Center'],
    assignedTo: '2',
    lastContactedAt: new Date('2024-01-20'),
    createdAt: new Date('2024-01-18'),
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    type: 'Apartment',
    location: 'Downtown',
    price: 950000,
    areaSqft: 1200,
    bed: 2,
    bath: 2,
    amenities: ['Gym', 'Pool', 'Parking', 'Concierge'],
    lat: 40.7589,
    lng: -73.9851,
    ownerName: 'Robert Brown',
    ownerPhone: '+1 555 0200',
    images: ['/placeholder-property-1.jpg'],
    createdAt: new Date('2024-01-05'),
    description: 'Stunning modern apartment with city views and premium amenities.',
  },
  {
    id: '2',
    title: 'Luxury Villa with Garden',
    type: 'Villa',
    location: 'Uptown',
    price: 1750000,
    areaSqft: 3500,
    bed: 4,
    bath: 3,
    amenities: ['Garden', 'Garage', 'Security', 'Smart Home'],
    lat: 40.7831,
    lng: -73.9712,
    ownerName: 'Lisa Thompson',
    ownerPhone: '+1 555 0201',
    images: ['/placeholder-property-2.jpg'],
    createdAt: new Date('2024-01-08'),
    description: 'Elegant villa featuring spacious rooms and beautiful garden.',
  },
  {
    id: '3',
    title: 'Waterfront Penthouse',
    type: 'Apartment',
    location: 'Waterfront',
    price: 2800000,
    areaSqft: 2400,
    bed: 3,
    bath: 3,
    amenities: ['Ocean View', 'Private Elevator', 'Terrace', 'Spa'],
    lat: 40.7505,
    lng: -74.0134,
    ownerName: 'James Wilson',
    ownerPhone: '+1 555 0202',
    images: ['/placeholder-property-3.jpg'],
    createdAt: new Date('2024-01-12'),
    description: 'Exclusive penthouse with panoramic ocean views and luxury finishes.',
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Jennifer Taylor',
    email: 'jennifer@email.com',
    phone: '+1 555 0300',
    preferences: {
      propertyType: ['Apartment', 'Villa'],
      locations: ['Downtown', 'Midtown'],
      budgetRange: [800000, 1500000],
      amenities: ['Gym', 'Pool', 'Parking'],
    },
    savedPropertyIds: ['1', '2'],
    loyaltyPoints: 150,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Michael Anderson',
    email: 'michael@email.com',
    phone: '+1 555 0301',
    preferences: {
      propertyType: ['Villa', 'Commercial'],
      locations: ['Uptown', 'Waterfront'],
      budgetRange: [1500000, 3000000],
      amenities: ['Garden', 'Security', 'Ocean View'],
    },
    savedPropertyIds: ['3'],
    loyaltyPoints: 275,
    createdAt: new Date('2023-12-15'),
  },
];

export const mockDeals: Deal[] = [
  {
    id: '1',
    leadId: '1',
    propertyId: '1',
    stage: 'Qualified',
    value: 950000,
    agentId: '2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '2',
    leadId: '2',
    propertyId: '2',
    stage: 'Negotiation',
    value: 1750000,
    agentId: '3',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    leadId: '3',
    propertyId: '3',
    stage: 'Visit',
    value: 2800000,
    agentId: '2',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Follow up with Alex Johnson',
    description: 'Discuss financing options and schedule property visit',
    dueAt: new Date('2024-01-25'),
    relatedType: 'Lead',
    relatedId: '1',
    assigneeId: '2',
    status: 'Open',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    title: 'Prepare contract for Villa sale',
    description: 'Draft purchase agreement for Maria Rodriguez',
    dueAt: new Date('2024-01-26'),
    relatedType: 'Deal',
    relatedId: '2',
    assigneeId: '3',
    status: 'Open',
    createdAt: new Date('2024-01-20'),
  },
];

export const mockMetrics: DashboardMetrics = {
  newLeads: 12,
  dealsInNegotiation: 8,
  closedDealsThisMonth: 5,
  totalRevenue: 8750000,
  conversionRate: 24,
  averageDealValue: 1750000,
};